EmpleoDotNet/Controllers/JobOpportunityController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using EmpleoDotNet.Core.Dto;
using EmpleoDotNet.Helpers;
using EmpleoDotNet.AppServices;
using EmpleoDotNet.Helpers.Alerts;
using EmpleoDotNet.Services.Social.Twitter;
using EmpleoDotNet.ViewModel;
using EmpleoDotNet.ViewModel.JobOpportunity;
using reCAPTCHA.MVC;
using System;
using System.Linq;
using System.Net;
using EmpleoDotNet.Core.Domain;
using EmpleoDotNet.ViewModel.JobOpportunityLike;
using Microsoft.AspNet.Identity;

namespace EmpleoDotNet.Controllers
{
    public class JobOpportunityController : EmpleoDotNetController
    {
        public ActionResult Index(JobOpportunityPagingParameter model)
        {
            var viewModel = GetSearchViewModel(model);

            if (!string.IsNullOrWhiteSpace(viewModel.SelectedLocationName) &&
                string.IsNullOrWhiteSpace(viewModel.SelectedLocationPlaceId))
            {
                ModelState.AddModelError("SelectedLocationName", "");
                return View(viewModel).WithError("Debe seleccionar una Localidad para buscar.");
            }

            var jobOpportunities = _jobOpportunityService.GetAllJobOpportunitiesPagedByFilters(model);

            viewModel.Result = jobOpportunities;

            return View(viewModel);
        }

        // GET: /JobOpportunity/Detail/4-jobtitle
        public ActionResult Detail(string id)
        {
            if (string.IsNullOrWhiteSpace(id))
                return RedirectToAction(nameof(Index));

            var jobOpportunityId = GetIdFromTitle(id);

            if (jobOpportunityId == 0)
                return RedirectToAction(nameof(Index));

            var viewModel = _jobOpportunityService.GetJobOpportunityById(jobOpportunityId);

            if (viewModel == null)
                return View(nameof(Index))
                    .WithError("La vacante solicitada no existe. Por favor escoge una vacante válida del listado");

            var expectedUrl = UrlHelperExtensions.SeoUrl(jobOpportunityId, viewModel.Title.SanitizeUrl());

            if (!expectedUrl.Equals(id, StringComparison.OrdinalIgnoreCase))
                return RedirectToActionPermanent(nameof(Detail), new { id = expectedUrl });

            ViewBag.RelatedJobs =
                _jobOpportunityService.GetCompanyRelatedJobs(jobOpportunityId, viewModel.CompanyName);

            ViewBag.CanLike = !CookieHelper.Exists(GetLikeCookieName(jobOpportunityId));

            var cookieView = $"JobView{viewModel.Id}";
            if (!CookieHelper.Exists(cookieView))
            {
                _jobOpportunityService.UpdateViewCount(viewModel.Id);
                CookieHelper.Set(cookieView, viewModel.Id.ToString());
            }

            return View(nameof(Detail), viewModel);
        }

        [HttpGet]

        [Authorize]
        public ActionResult New()
        {
            var viewModel = new NewJobOpportunityViewModel();

            return View(viewModel)
                .WithInfo("Prueba nuestro nuevo proceso guiado de creación de posiciones haciendo <b><a href='" + Url.Action("Wizard") + "'>click aquí</a></b>");
        }

        [HttpPost, ValidateAntiForgeryToken]
        [ValidateInput(false)]
        [CaptchaValidator(RequiredMessage = "Por favor confirma que no eres un robot")]
        [Authorize]
        public async Task<ActionResult> New(NewJobOpportunityViewModel model, bool captchaValid)
        {
            if (!ModelState.IsValid)
            {
                return View(model)
                    .WithError("Han ocurrido errores de validación que no permiten continuar el proceso");
            }

            if (string.IsNullOrWhiteSpace(model.LocationPlaceId))
            {
                ModelState.AddModelError(nameof(model.LocationName), "");
                return View(model).WithError("Debe seleccionar una Localidad.");
            }

            var jobOpportunity = model.ToEntity();
            var userId = User.Identity.GetUserId();

            _jobOpportunityService.CreateNewJobOpportunity(jobOpportunity, userId);

            await _twitterService.PostNewJobOpportunity(jobOpportunity).ConfigureAwait(false);

            return RedirectToAction(nameof(Detail), new {
                id = UrlHelperExtensions.SeoUrl(jobOpportunity.Id, jobOpportunity.Title)
            });
        }

        [HttpGet]
        public ActionResult Wizard()
        {
            var viewModel = new Wizard();

            return View(viewModel);
        }

        [HttpPost, ValidateAntiForgeryToken]
        [ValidateInput(false)]
        [CaptchaValidator(RequiredMessage = "Por favor confirma que no eres un robot")]
        public async Task<ActionResult> Wizard(Wizard model)
        {
            if (!ModelState.IsValid)
                return View(model)
                    .WithError("Han ocurrido errores de validación que no permiten continuar el proceso");

            var jobOpportunity = model.ToEntity();

            _jobOpportunityService.CreateNewJobOpportunity(jobOpportunity, User.Identity.GetUserId());

            await _twitterService.PostNewJobOpportunity(jobOpportunity);

            return RedirectToAction(nameof(Detail), new {
                id = UrlHelperExtensions.SeoUrl(jobOpportunity.Id, jobOpportunity.Title),
                fromWizard = 1
            });
        }

        [HttpPost]
        public JsonResult Like(JobOpportunityLike model)
        {
            var cookieName = GetLikeCookieName(model.JobOpportunityId);
            
            if (CookieHelper.Exists(cookieName))
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(new { error = true, message = "Ya has votado por este empleo." });
            }

            _jobOpportunityLikeService.CreateNewLike(model);

            CookieHelper.Set(cookieName, model.JobOpportunityId.ToString());

            var jobLikeData = _jobOpportunityLikeService.GetLikesByJobOpportunityId(model.JobOpportunityId);

            var jobOpportunityLikeData = new JobOpportunityLikeViewModel
            {
                Likes = jobLikeData.Count(x => x.Like),
                DisLikes = jobLikeData.Count(x => !x.Like)
            };
                
            return Json(new { error = false, data = jobOpportunityLikeData });
        }

        /// <summary>
        /// Transform JobOpportunityPagingParameter into JobOpportunitySearchViewModel with Locations
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        private JobOpportunitySearchViewModel GetSearchViewModel(JobOpportunityPagingParameter model)
        {
            if (string.IsNullOrWhiteSpace(model.SelectedLocationName))
            {
                model.SelectedLocationLatitude = string.Empty;
                model.SelectedLocationLongitude = string.Empty;
                model.SelectedLocationPlaceId = string.Empty;
            }

            var viewModel = new JobOpportunitySearchViewModel {
                SelectedLocationPlaceId = model.SelectedLocationPlaceId,
                SelectedLocationName = model.SelectedLocationName,
                SelectedLocationLongitude = model.SelectedLocationLongitude,
                SelectedLocationLatitude = model.SelectedLocationLatitude,
                JobCategory = model.JobCategory,
                Keyword = model.Keyword,
                IsRemote = model.IsRemote,
                CategoriesCount = _jobOpportunityService.GetMainJobCategoriesCount(),
            };

            return viewModel;
        }

        private static string GetLikeCookieName(int jobOpportunityId)
        {
            return $"JobLike{jobOpportunityId}";
        }

        private static int GetIdFromTitle(string title)
        {
            int id;
            var url = title.Split('-');

            if (string.IsNullOrEmpty(title) || url.Length == 0 || !int.TryParse(url[0], out id))
                return 0;

            return id;
        }

        public JobOpportunityController(
            IJobOpportunityService jobOpportunityService,
            ITwitterService twitterService, 
            IJobOpportunityLikeService jobOpportunityLikeService)
        {
            _jobOpportunityService = jobOpportunityService;
            _twitterService = twitterService;
            _jobOpportunityLikeService = jobOpportunityLikeService;
        }

        private readonly IJobOpportunityService _jobOpportunityService;
        private readonly ITwitterService _twitterService;
        private readonly IJobOpportunityLikeService _jobOpportunityLikeService;
    }
}

EmpleoDotNet/Views/JobOpportunity/Index.cshtml
@using PagedList.Mvc
@model EmpleoDotNet.ViewModel.JobOpportunitySearchViewModel

@{
    ViewBag.Title = "Listado de Empleos";
}

@* This added here because the partial view _FindsJobPartinal need this JS to work :( *@
@section scripts {
    <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?libraries=places"></script>
    <script type="text/javascript">

        google.maps.event.addDomListener(window, 'load', function () {
            var places = new google.maps.places.Autocomplete(document.getElementById('location-input'));
            google.maps.event.addListener(places, 'place_changed', function () {
                var place = places.getPlace();
                if (place) {
                    var placeId = place.place_id;
                    var latitude = place.geometry.location.lat();
                    var longitude = place.geometry.location.lng();

                    $('#location-placeid').val(placeId);
                    $('#location-latitude').val(latitude);
                    $('#location-longitude').val(longitude);
                } else {
                    $('#location-input').val('');
                    $('#location-placeid').val('');
                }
            });
        });
    </script>
}

@Html.Partial("_FindJobsPartial", Model)

<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12">
            @if (Model.Result == null || !Model.Result.Any())
            {
                <div>
                    <h5>No se encontraron resultados para esta búsqueda.</h5>
                    <hr/>
                </div>
            }
            else
            {
                <div>
                    <h5>@Model.Result.TotalItemCount Empleo(s) disponibles para esta búsqueda.</h5>
                </div>

                <br />

                @Html.Partial("_JobListPartial", Model.Result)

                <br />

                @*Pagination*@
                if (Model.Result.PageCount > 1)
                {
                   @Html.PagedListPager(Model.Result, page => Url.Action("Index", new
                    {
                       Model.SelectedLocationName,
                       Model.SelectedLocationLatitude,
                       Model.SelectedLocationLongitude,
                       Model.SelectedLocationPlaceId,
                       page,
                       Model.Result.PageSize
                   }))
                }
            }
        </div>
    </div>
</div>

EmpleoDotNet/Views/JobOpportunity/New.cshtml
@using EmpleoDotNet.Helpers
@using reCAPTCHA.MVC
@model EmpleoDotNet.ViewModel.NewJobOpportunityViewModel

@{
    ViewBag.Title = "Nuevo Empleo";
}
@section styles{
<style>
    #Description {
        height: 200px;
    }
</style>
}

@section scripts {
    <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?libraries=places"></script>
    <script type="text/javascript">
        
        google.maps.event.addDomListener(window, 'load', function () {
            var places = new google.maps.places.Autocomplete(document.getElementById('location-input'));
            google.maps.event.addListener(places, 'place_changed', function () {
                var place = places.getPlace();
                if (place) {
                    var latitude = place.geometry.location.lat();
                    var longitude = place.geometry.location.lng();
                    var placeId = place.place_id;

                    $('#location-latitude').val(latitude);
                    $('#location-longitude').val(longitude);
                    $('#location-placeid').val(placeId);
                } else {
                    $('#location-input').val('');
                    $('#location-latitude').val('');
                    $('#location-longitude').val('');
                    $('#location-placeid').val('');
                }        
            });
        });
    </script>
}

@using (Html.BeginForm("New", "JobOpportunity", FormMethod.Post, new { role = "form" }))
{
    @Html.AntiForgeryToken()

<div class="container" style="margin-top: 55px;">
    <div class="row">
        @*Job Details*@
        <div class="col-sm-6">
            <h2>Detalles del puesto</h2>
            <div class="form-group" id="job-title-group">
                <label for="Title">Título</label>
                @Html.TextBoxFor(m => m.Title, new { @class = "form-control", placeholder = "ejemp. Web Designer" })
                @Html.ValidationMessageFor(m => m.Title)
            </div>
            <div class="form-group" id="job-location-group">
                <label for="Location">Localidad</label>
                @Html.TextBoxFor(m => m.LocationName, new
                {
                    @class = "form-control",
                    placeholder = "Selecciona una localidad",
                    id = "location-input",
                    autocomplete = "off"
                })
                @Html.HiddenFor(m => m.LocationLatitude, new { id = "location-latitude"})
                @Html.HiddenFor(m => m.LocationLongitude, new { id = "location-longitude" })
                @Html.HiddenFor(m => m.LocationPlaceId, new { id = "location-placeid" })
            </div>
            <div class="form-group" id="job-category-group">
                <label for="Category">Categoría</label>
                @Html.EnumDropListFor(e => e.Category, new { @class = "form-control", id = "category" })
            </div>
            <div class="form-group" id="job-category-group">
                @Html.LabelFor(m => m.JobType)
                @Html.EnumDropListFor(e => e.JobType, new { @class = "form-control", id = "job-type" })
            </div>
            <div class="form-group">
                @Html.CheckBoxFor(m => m.IsRemote)
                <label for="IsRemote">Remoto?</label>
            </div>
        </div>

        @*Company Details*@
        <div class="col-sm-6">
            <h2>Detalles de la Empresa</h2>
            <div class="form-group" id="company-name-group">
                <label for="CompanyName">Nombre de la Empresa</label>
                @Html.TextBoxFor(m => m.CompanyName, new { @class = "form-control", placeholder = "CompanyX, SRL." })
                @Html.ValidationMessageFor(m => m.CompanyName)
            </div>
            <div class="form-group" id="company-email-group">
                <label for="CompanyEmail">Email</label>
                @Html.TextBoxFor(m => m.CompanyEmail, new { @class = "form-control", placeholder = "email@companyx.com" })
                @Html.ValidationMessageFor(m => m.CompanyEmail)
            </div>
            <div class="form-group" id="how-apply-group">  
                @Html.LabelFor(m => m.HowToApply)       
                @Html.TextAreaFor(m => m.HowToApply, new { @class = "form-control textarea" })
                @Html.ValidationMessageFor(m => m.HowToApply)
            </div>
            <div class="form-group" id="company-website-group">
                <label for="CompanyUrl">Web Site (Opcional)</label>
                @Html.TextBoxFor(m => m.CompanyUrl, new { @class = "form-control", placeholder = "companyx.com" })
                @Html.ValidationMessageFor(m => m.CompanyUrl)
            </div>
            <div class="form-group" id="company-logo-group">
                <label for="CompanyLogoUrl">Logo (Opcional)</label>
                @Html.TextBoxFor(m => m.CompanyLogoUrl, new { @class = "form-control", placeholder = "http://companyx.com/logo.png" })
                @Html.ValidationMessageFor(m => m.CompanyLogoUrl)
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <div class="form-group" id="job-description-group">
                <h2>Descripcion del Puesto</h2>
                @Html.TextAreaFor(m => m.Description, new { @class = "form-control textarea" })
                @Html.ValidationMessageFor(m => m.Description)
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <div class="form-group">
                @Html.Recaptcha()
                @Html.ValidationMessage("ReCaptcha")
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <button type="submit" class="btn btn-primary btn-lg">Crear Empleo</button>
        </div>
    </div>
</div>
}

EmpleoDotNet/Views/JobOpportunity/Wizard.cshtml
@using EmpleoDotNet.Helpers
@using reCAPTCHA.MVC
@model EmpleoDotNet.ViewModel.JobOpportunity.Wizard

@{
    ViewBag.Title = "Nuevo Empleo";
}

<section>
    <div class="container">
    @using (Html.BeginForm("Wizard", "JobOpportunity", FormMethod.Post, new {role = "form"}))
    {
        @Html.AntiForgeryToken()
        <div>
            <span class="h2 section-title"></span>
            <hr />
            <div class="tab section-1">1</div>
            <div class="tab section-2">2</div>
            <div class="tab section-3">3</div>
        </div>
        <div id="wizard" class="owl-carousel owl-theme">
            <div class="item" data-parsley-group="business-details">
                <div class="form-group" id="company-name-group">
                    @Html.LabelFor(m => m.CompanyName)
                    @Html.TextBoxFor(m => m.CompanyName, new {@class = "form-control", placeholder = "CompanyX, SRL.", required="", @data_parsley_group= "business-details"})
                    <span><b>Tip:</b> Los mejores candidatos tienden a hacer caso omiso de propuestas an&oacute;nimas</span>
                    @Html.ValidationMessageFor(m => m.CompanyName)
                </div>
                <div class="form-group" id="company-email-group">
                    @Html.LabelFor(m => m.CompanyEmail)
                    @Html.TextBoxFor(m => m.CompanyEmail, new {@class = "form-control", type="email", placeholder = "email@companyx.com", required = "", @data_parsley_group = "business-details" })
                    @Html.ValidationMessageFor(m => m.CompanyEmail)
                </div>          
                <div class="form-group" id="company-website-group">
                    @Html.LabelFor(m => m.CompanyUrl)
                    @Html.TextBoxFor(m => m.CompanyUrl, new {@class = "form-control", type="url", @data_parsley_type="url", placeholder = "companyx.com", @data_parsley_group = "business-details" })
                    <span>
                        <b>Tip:</b> Muchos aplicantes visitar&aacute;n tu sitio web y lo tomar&aacute;n 
                        como referencia antes de decidirse por t&iacute;. Si tu empresa no tiene un sitio web 
                        o crees que necesita unas mejoras, considera buscar un web developer en
                         <a href="@Url.Action("Index", "Home")">emplea.do</a>
                    </span>
                    @Html.ValidationMessageFor(m => m.CompanyUrl)
                </div>
                <div class="form-group" id="company-logo-group">
                    @Html.LabelFor(m => m.CompanyLogoUrl)
                    @Html.TextBoxFor(m => m.CompanyLogoUrl, new {@class = "form-control", type = "url", @data_parsley_type = "url", placeholder = "http://companyx.com/logo.png"})
                    <span>Asegurate de que el servidor donde est&eacute; alojado el logo acepte hotlinks. 
                    Si no sabes que es eso, no te preocupes, sube el logo a <a href="https://imgur.com" target="_blank">imgur</a> y pega la url aqu&iacute;</span>
                    @Html.ValidationMessageFor(m => m.CompanyLogoUrl)
                </div>
                <a class="btn-next btn btn-primary btn-lg">Siguiente</a>
            </div>
            <div class="item" data-parsley-group="job-details">
                <div class="form-group" id="job-title-group">
                    @Html.LabelFor(m => m.Title)
                    @Html.TextBoxFor(m => m.Title, new {@class = "form-control", placeholder = "ejemp. Se busca Web Designer", @data_parsley_group = "job-details", required="" })
                    @Html.ValidationMessageFor(m => m.Title)
                </div>
                <div class="form-group" id="job-category-group">
                    @Html.LabelFor(m => m.Category)
                    @Html.EnumDropListFor(e => e.Category, new {@class = "form-control", id = "category", @data_parsley_group = "job-details"})
                </div>
                <div class="form-group" id="job-category-group">
                    @Html.LabelFor(m => m.JobType)
                    @Html.EnumDropListFor(e => e.JobType, new { @class = "form-control", id = "job-type" })
                </div>

                <div class="form-group" id="how-apply-group">
                    @Html.LabelFor(m => m.HowToApply)
                    @Html.TextAreaFor(m => m.HowToApply, new { @class = "form-control textarea", required = "", @data_parsley_group = "job-details" })
                    @Html.ValidationMessageFor(m => m.HowToApply)
                </div>

                <div class="form-group" id="job-location-group">
                    @Html.LabelFor(m => m.LocationName)
                    @Html.TextBoxFor(m => m.LocationName, new
                   {
                       @class = "form-control",
                       placeholder = "Selecciona una localidad",
                       id = "location-input",
                       @data_parsley_group = "job-details",
                       autocomplete = "off"
                   })
                    @Html.HiddenFor(m => m.LocationLatitude, new { id = "location-latitude", @data_parsley_group = "job-details" })
                    @Html.HiddenFor(m => m.LocationLongitude, new { id = "location-longitude", @data_parsley_group = "job-details" })
                    @Html.HiddenFor(m => m.LocationPlaceId, new { id = "location-placeid", @data_parsley_group = "job-details" })
                </div>
                <div class="form-group">
                    @Html.CheckBoxFor(m => m.IsRemote)
                    @Html.LabelFor(m => m.IsRemote)
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.Description)
                    @Html.TextAreaFor(m => m.Description, new { @class = "form-control textarea", @data_parsley_group="job-details", @data_parsley_errors_container="#description_errors", required="" })
                    @Html.ValidationMessageFor(m => m.Description)
                    <span><b>Tip:</b> Se lo mas explicito posible, si eres de recursos humanos consulta con una persona de 
                    tecnolog&iacute;a sobre cuales son los requerimientos t&eacute;cnicos.</span>
                    <span id="description_errors" class="danger"></span>
                </div>
                <a class="btn-prev btn btn-warning btn-lg">Anterior</a>
                <a class="btn-next btn btn-primary btn-lg">Siguiente</a>

            </div>
            <div class="item">
                <p>Si no sabes que es puedes 
                <a href="http://local.joelonsoftware.com/wiki/El_Test_de_Joel:_12_pasos_hacia_un_c%C3%B3digo_mejor" target="_blank">leer aqu&iacute;</a>.
                    En resumen, es un cuestionario para medir la calidad del equipo de desarrollo de tu empresa. Coteja las opciones que apliquen.
                    <br/>**Este paso es opcional y solo aplica para posiciones relacionadas al Desarrollo de Software</p>
                <div class="form-group">
                    @Html.CheckBoxFor(m => m.HasSourceControl)
                    @Html.LabelFor(m => m.HasSourceControl)
                </div>
                <div class="form-group">
                    @Html.CheckBoxFor(m => m.HasOneStepBuilds)
                    @Html.LabelFor(m => m.HasOneStepBuilds)
                </div>
                <div class="form-group">
                    @Html.CheckBoxFor(m => m.HasDailyBuilds)
                    @Html.LabelFor(m => m.HasDailyBuilds)
                </div>
                <div class="form-group">
                    @Html.CheckBoxFor(m => m.HasBugDatabase)
                    @Html.LabelFor(m => m.HasBugDatabase)
                </div>
                <div class="form-group">
                    @Html.CheckBoxFor(m => m.HasBusFixedBeforeProceding)
                    @Html.LabelFor(m => m.HasBusFixedBeforeProceding)
                </div>
                <div class="form-group">
                    @Html.CheckBoxFor(m => m.HasUpToDateSchedule)
                    @Html.LabelFor(m => m.HasUpToDateSchedule)
                </div>
                <div class="form-group">
                    @Html.CheckBoxFor(m => m.HasSpec)
                    @Html.LabelFor(m => m.HasSpec)
                </div>
                <div class="form-group">
                    @Html.CheckBoxFor(m => m.HasQuiteEnvironment)
                    @Html.LabelFor(m => m.HasQuiteEnvironment)
                </div>
                <div class="form-group">
                    @Html.CheckBoxFor(m => m.HasBestTools)
                    @Html.LabelFor(m => m.HasBestTools)
                </div>
                <div class="form-group">
                    @Html.CheckBoxFor(m => m.HasTesters)
                    @Html.LabelFor(m => m.HasTesters)
                </div>
                <div class="form-group">
                    @Html.CheckBoxFor(m => m.HasWrittenTest)
                    @Html.LabelFor(m => m.HasWrittenTest)
                </div>
                <div class="form-group">
                    @Html.CheckBoxFor(m => m.HasHallwayTests)
                    @Html.LabelFor(m => m.HasHallwayTests)
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group">
                            @Html.Recaptcha()
                            @Html.ValidationMessage("ReCaptcha")
                        </div>
                    </div>
                </div>
                <a class="btn-prev btn btn-warning btn-lg">Anterior</a>
                <button type="submit" class="btn btn-primary btn-lg">Crear Empleo</button>
            </div>
        </div>
    }
    </div>
</section>
@section styles{
    <link href="~/Content/JobOpportunity/Wizard.css" rel="stylesheet" />
}
@section scripts {
    <script type="text/javascript" src="~/Scripts/parsley.min.js"></script>
    <script type="text/javascript" src="~/Scripts/i18n/parsley/es.js"></script>
    <script type="text/javascript" src="~/Scripts/JobOpportunity/Wizard.js"></script>
    <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?libraries=places"></script>
    <script type="text/javascript">
        google.maps.event.addDomListener(window, 'load', function () {
            var places = new google.maps.places.Autocomplete(document.getElementById('location-input'));
            google.maps.event.addListener(places, 'place_changed', function () {
                var place = places.getPlace();
                if (place) {
                    var latitude = place.geometry.location.lat();
                    var longitude = place.geometry.location.lng();
                    var placeId = place.place_id;

                    $('#location-latitude').val(latitude);
                    $('#location-longitude').val(longitude);
                    $('#location-placeid').val(placeId);
                } else {
                    $('#location-input').val('');
                    $('#location-latitude').val('');
                    $('#location-longitude').val('');
                    $('#location-placeid').val('');
                }
            });
        });
    </script>
}

EmpleoDotNet/Views/JobOpportunity/_JoelTestResults.cshtml
@using EmpleoDotNet.Helpers
@model EmpleoDotNet.Core.Domain.JoelTest

<h4>La prueba de JOEL</h4>
<p>Es un cuestionario para medir la calidad del equipo de desarrollo de tu empresa. Coteja las opciones que apliquen.
    <br />Esto es opcional y solo aplica para posiciones relacionadas al Desarrollo de Software
</p>
<div class="list-group">
    <div class="list-group-item">
        <b>¿Usan algún tipo de control de versiones? (Git, Subversion)</b> <span class="pull-right">@Html.Raw(Model.HasSourceControl.ToCheckTimesString())</span>
</div>
    <div class="list-group-item">
        <b>¿Pueden hacer pases a producción en un solo paso?</b> <span class="pull-right">@Html.Raw(Model.HasOneStepBuilds.ToCheckTimesString())</span>
    </div>
    <div class="list-group-item">
        <b>¿Compilan el producto diariamente?</b> <span class="pull-right">@Html.Raw(Model.HasDailyBuilds.ToCheckTimesString())</span>
    </div>
    <div class="list-group-item">
        <b>¿Tienen una base de datos de bugs?</b> <span class="pull-right">@Html.Raw(Model.HasBugDatabase.ToCheckTimesString())</span>
    </div>
    <div class="list-group-item">
        <b>¿Corrigen los bugs antes de añadir más código?</b> <span class="pull-right">@Html.Raw(Model.HasBusFixedBeforeProceding.ToCheckTimesString())</span>
    </div>
    <div class="list-group-item">
        <b>¿Tienen una planificación actualizada?</b> <span class="pull-right">@Html.Raw(Model.HasUpToDateSchedule.ToCheckTimesString())</span>
    </div>
    <div class="list-group-item">
        <b>¿Tienes un documento de especificaciones?</b> <span class="pull-right">@Html.Raw(Model.HasSpec.ToCheckTimesString())</span>
    </div>
    <div class="list-group-item">
        <b>¿Están los programadores en un lugar tranquilo?</b> <span class="pull-right">@Html.Raw(Model.HasQuiteEnvironment.ToCheckTimesString())</span>
    </div>
    <div class="list-group-item">
        <b>¿Utilizan las mejores herramientas que puedes comprar?</b> <span class="pull-right">@Html.Raw(Model.HasBestTools.ToCheckTimesString())</span>
    </div>
    <div class="list-group-item">
        <b>¿Tienen gente para probar los productos?</b> <span class="pull-right">@Html.Raw(Model.HasTesters.ToCheckTimesString())</span>
    </div>
    <div class="list-group-item">
        <b>¿Hacen escribir código a los nuevos candidatos en las entrevistas?</b> <span class="pull-right">@Html.Raw(Model.HasWrittenTest.ToCheckTimesString())</span>
    </div>
    <div class="list-group-item">
        <b>¿Hacen pruebas de usabilidad 'de vestíbulo'?</b> <span class="pull-right">@Html.Raw(Model.HasHallwayTests.ToCheckTimesString())</span>
    </div>
</div>